INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('jim', 'cars', 1000, 1227, 1228);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('jim', 'cars', 1000, 1227, 1228);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('jim', 'cars', 1000, 1227, 1228);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('jim', 'cars', 1000, 1227, 1228);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('jim', 'cars', 1000, 1227, 1228);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('jim', 'cars', 1000, 1227, 1228);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('jim', 'cars', 1000, 1227, 1228);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('jim', 'cars', 1000, 1227, 1228);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('jim', 'cars', 1000, 1227, 1228);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('jim', 'cars', 1000, 1227, 1228);
INSERT INTO users (name, age) VALUES ('gary', 28);
INSERT INTO users (name, age) VALUES ('gary', 28);
INSERT INTO users (name, age) VALUES ('gary', 28);
INSERT INTO users (name, age) VALUES ('gary', 28);
INSERT INTO users (name, age) VALUES ('gary', 28);
INSERT INTO users (name, age) VALUES ('gary', 28);
INSERT INTO users (name, age) VALUES ('gary', 28);
INSERT INTO users (name, age) VALUES ('gary', 28);
INSERT INTO users (name, age) VALUES ('gary', 28);
INSERT INTO users (name, age) VALUES ('gary', 28);
INSERT INTO users (name, age) VALUES ('gary', 28);
INSERT INTO users (name, age) VALUES ('gary', 28);
INSERT INTO users (name, age) VALUES ('gary', 28);
INSERT INTO users (name, age) VALUES ('gary', 28);
INSERT INTO users (name, age) VALUES ('gary', 28);
INSERT INTO users (name, age) VALUES ('gary', 28);
INSERT INTO users (name, age) VALUES ('gary', 28);
INSERT INTO users (name, age) VALUES ('gary', 28);
INSERT INTO users (name, age) VALUES ('gary', 28);
INSERT INTO users (name, age) VALUES ('gary', 28);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10000, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10000, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10000, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10000, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10000, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10000, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10000, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10000, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10000, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10000, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10000, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10000, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10000, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10000, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10000, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10000, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10000, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10000, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10000, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10000, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10000, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10000, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10000, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10000, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10000, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10000, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10000, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10000, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10000, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10000, 1, 2);